(define (problem 2ndex_familyvacation) 
 
 (:domain 2ndex_familyvacation) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-dates) 
 	(executed-build) 
 	(executed-list interests family) 
 	(executed-travel airplane destination) 
 	(executed-drive vacation vacation) 
 	(executed-purchase tickets) 
 	(executed-get passport) 
 	(executed-keep schedule) 
 	(=(number-executed-dates) 0) 
 	(=(number-executed-build) 0) 
 	(=(number-executedDObIOb-list interests family) 0) 
 	(=(number-executedDObIOb-destination your your) 0) 
 	(=(number-executedDObIOb-travel airplane destination) 0) 
 	(=(number-executedDObIOb-vacation your your) 0) 
 	(=(number-executedDObIOb-drive vacation vacation) 0) 
 	(=(number-executedDObIOb-family your your) 0) 
 	(=(number-executedDObIOb-memories family family) 0) 
 	(=(number-executedDObIOb-allow activities activities) 0) 
 	(=(number-executedDObIOb-plan time time) 0) 
 	(=(number-executedIOb-plan potential) 0) 
 	(=(number-executedIOb-purchase tickets) 0) 
 	(=(number-executedIOb-get passport) 0) 
 	(=(number-executedIOb-keep schedule) 0) 
 	(property-as family) 
 	(property-for potential) 
 	(property-on airplane) 
 	(property-to destination) 
 	(property-to vacation) 
 	(property-poss your) 
 	(property-with family) 
 	(property-for activities) 
 	(property-for time) 
 	(property-other activities) 
 	(property-open schedule) 
 	(property-build memories) 
 	(property-different activities) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-dates) 1) 
 	(=(number-executed-build) 1) 
 	(=(number-executedDObIOb-list interests family) 1) 
 	(=(number-executedDObIOb-destination your your) 1) 
 	(=(number-executedDObIOb-travel airplane destination) 1) 
 	(=(number-executedDObIOb-vacation your your) 1) 
 	(=(number-executedDObIOb-drive vacation vacation) 1) 
 	(=(number-executedDObIOb-family your your) 1) 
 	(=(number-executedDObIOb-memories family family) 1) 
 	(=(number-executedDObIOb-allow activities activities) 1) 
 	(=(number-executedDObIOb-plan time time) 1) 
 	(=(number-executedIOb-plan potential) 1) 
 	(=(number-executedIOb-purchase tickets) 1) 
 	(=(number-executedIOb-get passport) 1) 
 	(=(number-executedIOb-keep schedule) 1) 
 	(finished)
)) 
 
)