(define (problem 2ndex_gingercookies) 
 
 (:domain 2ndex_gingercookies) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-cream) 
 	(executed-pour mixture bowl) 
 	(executed-form batter ball) 
 	(executed-beat ingredients) 
 	(executed-mix ingredients) 
 	(executed-stir ingredients) 
 	(executed-use spoon) 
 	(=(number-executed-cut) 0) 
 	(=(number-executed-cream) 0) 
 	(=(number-executedDObIOb-put flour bowl) 0) 
 	(=(number-executedDObIOb-put salt bowl) 0) 
 	(=(number-executedDObIOb-put cinnamon bowl) 0) 
 	(=(number-executedDObIOb-put ginger bowl) 0) 
 	(=(number-executedDObIOb-put cloves bowl) 0) 
 	(=(number-executedDObIOb-place egg bowl) 0) 
 	(=(number-executedDObIOb-place vanilla bowl) 0) 
 	(=(number-executedDObIOb-place molasses bowl) 0) 
 	(=(number-executedDObIOb-pour mixture bowl) 0) 
 	(=(number-executedDObIOb-form batter ball) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-butter bowl bowl) 0) 
 	(=(number-executedDObIOb-sugar bowl bowl) 0) 
 	(=(number-executedIOb-stir ingredients) 0) 
 	(=(number-executedIOb-add ingredients) 0) 
 	(=(number-executedIOb-beat ingredients) 0) 
 	(=(number-executedIOb-mix ingredients) 0) 
 	(=(number-executedIOb-use spoon) 0) 
 	(=(number-executedIOb-chill it) 0) 
 	(=(number-executedIOb-roll dough) 0) 
 	(=(cut-saliency) 1) 
 	(=(cream-saliency) 1) 
 	(=(put-saliency flour bowl) 1) 
 	(=(put-saliency salt bowl) 1) 
 	(=(put-saliency cinnamon bowl) 1) 
 	(=(put-saliency ginger bowl) 1) 
 	(=(put-saliency cloves bowl) 1) 
 	(=(place-saliency egg bowl) 1) 
 	(=(place-saliency vanilla bowl) 1) 
 	(=(place-saliency molasses bowl) 1) 
 	(=(pour-saliency mixture bowl) 1) 
 	(=(form-saliency batter ball) 1) 
 	(=(preheat-saliency oven f) 1) 
 	(=(butter-saliency bowl bowl) 1) 
 	(=(sugar-saliency bowl bowl) 1) 
 	(=(stir-saliency ingredients) 1) 
 	(=(add-saliency ingredients) 1) 
 	(=(beat-saliency ingredients) 1) 
 	(=(mix-saliency ingredients) 1) 
 	(=(use-saliency spoon) 1) 
 	(=(chill-saliency it) 1) 
 	(=(roll-saliency dough) 1) 
 	(property-in bowl) 
 	(property-to bowl) 
 	(property-into ball) 
 	(property-to f) 
 	(property-baking soda) 
 	(property-wet ingredients) 
 	(property-dry ingredients) 
 	(property-wet bowl) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-cut) 1) 
 	(=(number-executed-cream) 1) 
 	(=(number-executedDObIOb-put flour bowl) 1) 
 	(=(number-executedDObIOb-put salt bowl) 1) 
 	(=(number-executedDObIOb-put cinnamon bowl) 1) 
 	(=(number-executedDObIOb-put ginger bowl) 1) 
 	(=(number-executedDObIOb-put cloves bowl) 1) 
 	(=(number-executedDObIOb-place egg bowl) 1) 
 	(=(number-executedDObIOb-place vanilla bowl) 1) 
 	(=(number-executedDObIOb-place molasses bowl) 1) 
 	(=(number-executedDObIOb-pour mixture bowl) 1) 
 	(=(number-executedDObIOb-form batter ball) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-butter bowl bowl) 1) 
 	(=(number-executedDObIOb-sugar bowl bowl) 1) 
 	(=(number-executedIOb-stir ingredients) 1) 
 	(=(number-executedIOb-add ingredients) 1) 
 	(=(number-executedIOb-beat ingredients) 1) 
 	(=(number-executedIOb-mix ingredients) 1) 
 	(=(number-executedIOb-use spoon) 1) 
 	(=(number-executedIOb-chill it) 1) 
 	(=(number-executedIOb-roll dough) 1) 
 	(finished)
)) 
 
)