(define (problem 2ndex_sushi2) 
 
 (:domain 2ndex_sushi2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-place seaweed mat) 
 	(executed-cover sheet rice) 
 	(executed-slice knife knife) 
 	(executed-roll it) 
 	(=(number-executed-cream) 0) 
 	(=(number-executedDObIOb-place seaweed mat) 0) 
 	(=(number-executedDObIOb-cover sheet rice) 0) 
 	(=(number-executedDObIOb-layer avocado rice) 0) 
 	(=(number-executedDObIOb-smooth paddle paddle) 0) 
 	(=(number-executedDObIOb-slice knife knife) 0) 
 	(=(number-executedDObIOb-serve sauce sauce) 0) 
 	(=(number-executedIOb-layer cheese) 0) 
 	(=(number-executedIOb-roll it) 0) 
 	(property-on mat) 
 	(property-of seaweed) 
 	(property-with rice) 
 	(property-with paddle) 
 	(property-on rice) 
 	(property-with knife) 
 	(property-with sauce) 
 	(property-sharp knife) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-cream) 1) 
 	(=(number-executedDObIOb-place seaweed mat) 1) 
 	(=(number-executedDObIOb-cover sheet rice) 1) 
 	(=(number-executedDObIOb-layer avocado rice) 1) 
 	(=(number-executedDObIOb-smooth paddle paddle) 1) 
 	(=(number-executedDObIOb-slice knife knife) 1) 
 	(=(number-executedDObIOb-serve sauce sauce) 1) 
 	(=(number-executedIOb-layer cheese) 1) 
 	(=(number-executedIOb-roll it) 1) 
 	(finished)
)) 
 
)