(define (problem 2ndex_raspberrycookies) 
 
 (:domain 2ndex_raspberrycookies) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-preheat oven f) 
 	(executed-put cookies sheet) 
 	(executed-stir chips) 
 	(executed-fold raspberries) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-combine flour bowl) 0) 
 	(=(number-executedDObIOb-combine salt bowl) 0) 
 	(=(number-executedDObIOb-add ingredients ingredients) 0) 
 	(=(number-executedDObIOb-put cookies sheet) 0) 
 	(=(number-executedIOb-mix butter) 0) 
 	(=(number-executedIOb-mix sugar) 0) 
 	(=(number-executedIOb-add eggs) 0) 
 	(=(number-executedIOb-add vanilla) 0) 
 	(=(number-executedIOb-stir chips) 0) 
 	(=(number-executedIOb-fold raspberries) 0) 
 	(property-to f) 
 	(property-in bowl) 
 	(property-to ingredients) 
 	(property-on sheet) 
 	(property-baking soda) 
 	(property-dry ingredients) 
 	(property-wet ingredients) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-combine flour bowl) 1) 
 	(=(number-executedDObIOb-combine salt bowl) 1) 
 	(=(number-executedDObIOb-add ingredients ingredients) 1) 
 	(=(number-executedDObIOb-put cookies sheet) 1) 
 	(=(number-executedIOb-mix butter) 1) 
 	(=(number-executedIOb-mix sugar) 1) 
 	(=(number-executedIOb-add eggs) 1) 
 	(=(number-executedIOb-add vanilla) 1) 
 	(=(number-executedIOb-stir chips) 1) 
 	(=(number-executedIOb-fold raspberries) 1) 
 	(finished)
)) 
 
)