(define (problem 2ndex_microwave_french_toast) 
 
 (:domain 2ndex_microwave_french_toast) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-continue) 
 	(executed-soak breads mixture) 
 	(executed-place breads plate) 
 	(executed-flip bread) 
 	(executed-put syrup) 
 	(executed-put fruit) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-continue) 0) 
 	(=(number-executedDObIOb-break eggs it) 0) 
 	(=(number-executedDObIOb-soak breads mixture) 0) 
 	(=(number-executedDObIOb-place breads plate) 0) 
 	(=(number-executedDObIOb-set microwave high) 0) 
 	(=(number-executedIOb-set bowl) 0) 
 	(=(number-executedIOb-flip bread) 0) 
 	(=(number-executedIOb-put syrup) 0) 
 	(=(number-executedIOb-put fruit) 0) 
 	(property-into it) 
 	(property-in mixture) 
 	(property-on plate) 
 	(property-for minutes) 
 	(property-on high) 
 	(property-wet mixture) 
 	(property-wet breads) 
 	(property-microwavable plate) 
 	(property-maple syrup) 
 	(property-fresh fruit) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-continue) 1) 
 	(=(number-executedDObIOb-break eggs it) 1) 
 	(=(number-executedDObIOb-soak breads mixture) 1) 
 	(=(number-executedDObIOb-place breads plate) 1) 
 	(=(number-executedDObIOb-set microwave high) 1) 
 	(=(number-executedIOb-set bowl) 1) 
 	(=(number-executedIOb-flip bread) 1) 
 	(=(number-executedIOb-put syrup) 1) 
 	(=(number-executedIOb-put fruit) 1) 
 	(finished)
)) 
 
)