(define (problem 2ndex_installamachine) 
 
 (:domain 2ndex_installamachine) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-choose spot) 
 	(executed-ensure fit) 
 	(executed-measure area) 
 	(executed-adjust feet) 
 	(executed-remove washer) 
 	(executed-connect hose) 
 	(executed-set hose) 
 	(executed-try run) 
 	(=(number-executed-use) 0) 
 	(=(number-executed-pan) 0) 
 	(=(number-executedIOb-choose spot) 0) 
 	(=(number-executedIOb-measure area) 0) 
 	(=(number-executedIOb-ensure fit) 0) 
 	(=(number-executedIOb-adjust feet) 0) 
 	(=(number-executedIOb-remove washer) 0) 
 	(=(number-executedIOb-connect hose) 0) 
 	(=(number-executedIOb-set hose) 0) 
 	(=(number-executedIOb-try run) 0) 
 	(property-poss your) 
 	(property-right spot) 
 	(property-proper fit) 
 	(property-old washer) 
 	(property-washing valve) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-use) 1) 
 	(=(number-executed-pan) 1) 
 	(=(number-executedIOb-choose spot) 1) 
 	(=(number-executedIOb-measure area) 1) 
 	(=(number-executedIOb-ensure fit) 1) 
 	(=(number-executedIOb-adjust feet) 1) 
 	(=(number-executedIOb-remove washer) 1) 
 	(=(number-executedIOb-connect hose) 1) 
 	(=(number-executedIOb-set hose) 1) 
 	(=(number-executedIOb-try run) 1) 
 	(finished)
)) 
 
)