(define (problem 2ndex_buttercookie2) 
 
 (:domain 2ndex_buttercookie2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-preheat oven f) 
 	(executed-press dough sheets) 
 	(executed-bake minutes minutes) 
 	(executed-take bowl) 
 	(executed-cover dough) 
 	(=(number-executed-cool) 0) 
 	(=(number-executedDObIOb-stir them sugar) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-press dough sheets) 0) 
 	(=(number-executedDObIOb-beat egg egg) 0) 
 	(=(number-executedDObIOb-stir vanilla vanilla) 0) 
 	(=(number-executedDObIOb-dough hour hour) 0) 
 	(=(number-executedDObIOb-bake minutes minutes) 0) 
 	(=(number-executedDObIOb-minutes oven oven) 0) 
 	(=(number-executedDObIOb-remove sheets sheets) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(number-executedIOb-cream butter) 0) 
 	(=(number-executedIOb-cream sugar) 0) 
 	(=(number-executedIOb-combine flour) 0) 
 	(=(number-executedIOb-combine salt) 0) 
 	(=(number-executedIOb-cover dough) 0) 
 	(=(number-executedIOb-chill sheets) 0) 
 	(=(cool-saliency) 1) 
 	(=(stir-saliency them sugar) 1) 
 	(=(preheat-saliency oven f) 1) 
 	(=(press-saliency dough sheets) 1) 
 	(=(beat-saliency egg egg) 1) 
 	(=(stir-saliency vanilla vanilla) 1) 
 	(=(dough-saliency hour hour) 1) 
 	(=(bake-saliency minutes minutes) 1) 
 	(=(minutes-saliency oven oven) 1) 
 	(=(remove-saliency sheets sheets) 1) 
 	(=(take-saliency bowl) 1) 
 	(=(cream-saliency butter) 1) 
 	(=(cream-saliency sugar) 1) 
 	(=(combine-saliency flour) 1) 
 	(=(combine-saliency salt) 1) 
 	(=(cover-saliency dough) 1) 
 	(=(chill-saliency sheets) 1) 
 	(property-in egg) 
 	(property-in vanilla) 
 	(property-into sugar) 
 	(property-for hour) 
 	(property-to f) 
 	(property-on sheets) 
 	(property-for minutes) 
 	(property-in oven) 
 	(property-from sheets) 
 	(property-large bowl) 
 	(property-white sugar) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-cool) 1) 
 	(=(number-executedDObIOb-stir them sugar) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-press dough sheets) 1) 
 	(=(number-executedDObIOb-beat egg egg) 1) 
 	(=(number-executedDObIOb-stir vanilla vanilla) 1) 
 	(=(number-executedDObIOb-dough hour hour) 1) 
 	(=(number-executedDObIOb-bake minutes minutes) 1) 
 	(=(number-executedDObIOb-minutes oven oven) 1) 
 	(=(number-executedDObIOb-remove sheets sheets) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(=(number-executedIOb-cream butter) 1) 
 	(=(number-executedIOb-cream sugar) 1) 
 	(=(number-executedIOb-combine flour) 1) 
 	(=(number-executedIOb-combine salt) 1) 
 	(=(number-executedIOb-cover dough) 1) 
 	(=(number-executedIOb-chill sheets) 1) 
 	(finished)
)) 
 
)