(define (problem 2ndex_ChocolateCookies2) 
 
 (:domain 2ndex_ChocolateCookies2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-whisk) 
 	(executed-roll it hands) 
 	(executed-flatten dough fork) 
 	(executed-put cookies oven) 
 	(executed-mix ingredients) 
 	(=(number-executed-whisk) 0) 
 	(=(number-executed-finish) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-add vanilla bowl) 0) 
 	(=(number-executedDObIOb-add sugar bowl) 0) 
 	(=(number-executedDObIOb-add eggs bowl) 0) 
 	(=(number-executedDObIOb-add butter bowl) 0) 
 	(=(number-executedDObIOb-add flour bowl) 0) 
 	(=(number-executedDObIOb-add salt bowl) 0) 
 	(=(number-executedDObIOb-add soda bowl) 0) 
 	(=(number-executedDObIOb-apply spray pan) 0) 
 	(=(number-executedDObIOb-roll it hands) 0) 
 	(=(number-executedDObIOb-flatten dough fork) 0) 
 	(=(number-executedDObIOb-put cookies oven) 0) 
 	(=(number-executedDObIOb-cool cookies minutes) 0) 
 	(=(number-executedDObIOb-wait minutes minutes) 0) 
 	(=(number-executedDObIOb-store container container) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(number-executedIOb-mix ingredients) 0) 
 	(=(number-executedIOb-take dough) 0) 
 	(=(number-executedIOb-cool cookies) 0) 
 	(property-to f) 
 	(property-to bowl) 
 	(property-to pan) 
 	(property-in hands) 
 	(property-on pan) 
 	(property-with fork) 
 	(property-in oven) 
 	(property-out_of oven) 
 	(property-for minutes) 
 	(property-in container) 
 	(property-brown sugar) 
 	(property-baking soda) 
 	(property-dry ingredients) 
 	(property-wet ingredients) 
 	(property-cooking spray) 
 	(property-baking pan) 
 	(property-airtight container) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-whisk) 1) 
 	(=(number-executed-finish) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-add vanilla bowl) 1) 
 	(=(number-executedDObIOb-add sugar bowl) 1) 
 	(=(number-executedDObIOb-add eggs bowl) 1) 
 	(=(number-executedDObIOb-add butter bowl) 1) 
 	(=(number-executedDObIOb-add flour bowl) 1) 
 	(=(number-executedDObIOb-add salt bowl) 1) 
 	(=(number-executedDObIOb-add soda bowl) 1) 
 	(=(number-executedDObIOb-apply spray pan) 1) 
 	(=(number-executedDObIOb-roll it hands) 1) 
 	(=(number-executedDObIOb-flatten dough fork) 1) 
 	(=(number-executedDObIOb-put cookies oven) 1) 
 	(=(number-executedDObIOb-cool cookies minutes) 1) 
 	(=(number-executedDObIOb-wait minutes minutes) 1) 
 	(=(number-executedDObIOb-store container container) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(=(number-executedIOb-mix ingredients) 1) 
 	(=(number-executedIOb-take dough) 1) 
 	(=(number-executedIOb-cool cookies) 1) 
 	(finished)
)) 
 
)