(define (problem 2ndex_microwave_french_toast_2) 
 
 (:domain 2ndex_microwave_french_toast_2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-place bread plate) 
 	(=(number-executedDObIOb-put them bowl) 0) 
 	(=(number-executedDObIOb-soak bread mixture) 0) 
 	(=(number-executedDObIOb-place bread plate) 0) 
 	(=(number-executedDObIOb-microwave minute high) 0) 
 	(=(number-executedDObIOb-repeat bread slices) 0) 
 	(=(number-executedDObIOb-garnish syrup syrup) 0) 
 	(=(number-executedIOb-whisk milk) 0) 
 	(=(number-executedIOb-whisk egg) 0) 
 	(=(number-executedIOb-whisk vanilla) 0) 
 	(=(number-executedIOb-whisk cinnamon) 0) 
 	(=(number-executedIOb-flip it) 0) 
 	(=(number-executedIOb-soak side) 0) 
 	(=(put-saliency them bowl) 1) 
 	(=(soak-saliency bread mixture) 1) 
 	(=(place-saliency bread plate) 1) 
 	(=(microwave-saliency minute high) 1) 
 	(=(repeat-saliency bread slices) 1) 
 	(=(garnish-saliency syrup syrup) 1) 
 	(=(whisk-saliency milk) 1) 
 	(=(whisk-saliency egg) 1) 
 	(=(whisk-saliency vanilla) 1) 
 	(=(whisk-saliency cinnamon) 1) 
 	(=(flip-saliency it) 1) 
 	(=(soak-saliency side) 1) 
 	(property-in bowl) 
 	(property-in mixture) 
 	(property-on plate) 
 	(property-for minute) 
 	(property-on high) 
 	(property-of bread) 
 	(property-with slices) 
 	(property-with syrup) 
 	(property-other side) 
 	(property-eggy bread) 
 	(property-microwavable plate) 
 	(property-other slices) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executedDObIOb-put them bowl) 1) 
 	(=(number-executedDObIOb-soak bread mixture) 1) 
 	(=(number-executedDObIOb-place bread plate) 1) 
 	(=(number-executedDObIOb-microwave minute high) 1) 
 	(=(number-executedDObIOb-repeat bread slices) 1) 
 	(=(number-executedDObIOb-garnish syrup syrup) 1) 
 	(=(number-executedIOb-whisk milk) 1) 
 	(=(number-executedIOb-whisk egg) 1) 
 	(=(number-executedIOb-whisk vanilla) 1) 
 	(=(number-executedIOb-whisk cinnamon) 1) 
 	(=(number-executedIOb-flip it) 1) 
 	(=(number-executedIOb-soak side) 1) 
 	(finished)
)) 
 
)