(define (problem 2ndex_doughicecreamcookie) 
 
 (:domain 2ndex_doughicecreamcookie) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-chips) 
 	(executed-pulse chips) 
 	(executed-fold ingredients) 
 	(executed-prepare tray) 
 	(=(number-executed-heat) 0) 
 	(=(number-executed-finished) 0) 
 	(=(number-executed-cream) 0) 
 	(=(number-executed-chips) 0) 
 	(=(number-executedDObIOb-fill bowl ice) 0) 
 	(=(number-executedDObIOb-whisk milk mixture) 0) 
 	(=(number-executedDObIOb-cool custard bath) 0) 
 	(=(number-executedDObIOb-whisk cream bowl) 0) 
 	(=(number-executedDObIOb-stir vanilla vanilla) 0) 
 	(=(number-executedDObIOb-stir salt salt) 0) 
 	(=(number-executedDObIOb-stir flour flour) 0) 
 	(=(number-executedDObIOb-store freezer freezer) 0) 
 	(=(number-executedDObIOb-combine machine machine) 0) 
 	(=(number-executedIOb-stir vanilla) 0) 
 	(=(number-executedIOb-stir salt) 0) 
 	(=(number-executedIOb-stir flour) 0) 
 	(=(number-executedIOb-stir chocolate) 0) 
 	(=(number-executedIOb-stir cream) 0) 
 	(=(number-executedIOb-pulse chips) 0) 
 	(=(number-executedIOb-prepare tray) 0) 
 	(=(number-executedIOb-whisk yolks) 0) 
 	(=(number-executedIOb-whisk salt) 0) 
 	(=(number-executedIOb-whisk sugar) 0) 
 	(=(number-executedIOb-set bath) 0) 
 	(=(number-executedIOb-fill water) 0) 
 	(=(number-executedIOb-combine custard) 0) 
 	(=(number-executedIOb-combine cream) 0) 
 	(=(number-executedIOb-fold ingredients) 0) 
 	(=(number-executedIOb-freeze cream) 0) 
 	(=(heat-saliency) 1) 
 	(=(finished-saliency) 1) 
 	(=(cream-saliency) 1) 
 	(=(chips-saliency) 1) 
 	(=(fill-saliency bowl ice) 1) 
 	(=(whisk-saliency milk mixture) 1) 
 	(=(cool-saliency custard bath) 1) 
 	(=(whisk-saliency cream bowl) 1) 
 	(=(stir-saliency vanilla vanilla) 1) 
 	(=(stir-saliency salt salt) 1) 
 	(=(stir-saliency flour flour) 1) 
 	(=(store-saliency freezer freezer) 1) 
 	(=(combine-saliency machine machine) 1) 
 	(=(stir-saliency vanilla) 1) 
 	(=(stir-saliency salt) 1) 
 	(=(stir-saliency flour) 1) 
 	(=(stir-saliency chocolate) 1) 
 	(=(stir-saliency cream) 1) 
 	(=(pulse-saliency chips) 1) 
 	(=(prepare-saliency tray) 1) 
 	(=(whisk-saliency yolks) 1) 
 	(=(whisk-saliency salt) 1) 
 	(=(whisk-saliency sugar) 1) 
 	(=(set-saliency bath) 1) 
 	(=(fill-saliency water) 1) 
 	(=(combine-saliency custard) 1) 
 	(=(combine-saliency cream) 1) 
 	(=(fold-saliency ingredients) 1) 
 	(=(freeze-saliency cream) 1) 
 	(property-in vanilla) 
 	(property-in salt) 
 	(property-in flour) 
 	(property-in chocolate) 
 	(property-in cream) 
 	(property-with ice) 
 	(property-into mixture) 
 	(property-in bath) 
 	(property-in bowl) 
 	(property-in freezer) 
 	(property-in machine) 
 	(property-baking tray) 
 	(property-cold water) 
 	(property-solid freeze) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-heat) 1) 
 	(=(number-executed-finished) 1) 
 	(=(number-executed-cream) 1) 
 	(=(number-executed-chips) 1) 
 	(=(number-executedDObIOb-fill bowl ice) 1) 
 	(=(number-executedDObIOb-whisk milk mixture) 1) 
 	(=(number-executedDObIOb-cool custard bath) 1) 
 	(=(number-executedDObIOb-whisk cream bowl) 1) 
 	(=(number-executedDObIOb-stir vanilla vanilla) 1) 
 	(=(number-executedDObIOb-stir salt salt) 1) 
 	(=(number-executedDObIOb-stir flour flour) 1) 
 	(=(number-executedDObIOb-store freezer freezer) 1) 
 	(=(number-executedDObIOb-combine machine machine) 1) 
 	(=(number-executedIOb-stir vanilla) 1) 
 	(=(number-executedIOb-stir salt) 1) 
 	(=(number-executedIOb-stir flour) 1) 
 	(=(number-executedIOb-stir chocolate) 1) 
 	(=(number-executedIOb-stir cream) 1) 
 	(=(number-executedIOb-pulse chips) 1) 
 	(=(number-executedIOb-prepare tray) 1) 
 	(=(number-executedIOb-whisk yolks) 1) 
 	(=(number-executedIOb-whisk salt) 1) 
 	(=(number-executedIOb-whisk sugar) 1) 
 	(=(number-executedIOb-set bath) 1) 
 	(=(number-executedIOb-fill water) 1) 
 	(=(number-executedIOb-combine custard) 1) 
 	(=(number-executedIOb-combine cream) 1) 
 	(=(number-executedIOb-fold ingredients) 1) 
 	(=(number-executedIOb-freeze cream) 1) 
 	(finished)
)) 
 
)