(define (problem 2ndex_lobstersushi) 
 
 (:domain 2ndex_lobstersushi) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-boil rice) 
 	(executed-cook ricet) 
 	(executed-whisk honey) 
 	(executed-whisk vinegar) 
 	(executed-add salt) 
 	(executed-wait minutes) 
 	(=(number-executed-serve) 0) 
 	(=(number-executedDObIOb-pour mixture rice) 0) 
 	(=(number-executedDObIOb-lay mat surface) 0) 
 	(=(number-executedDObIOb-sprinkle rice nori) 0) 
 	(=(number-executedDObIOb-sprinkle mixture rice) 0) 
 	(=(number-executedDObIOb-lay pieces nori) 0) 
 	(=(number-executedDObIOb-lay slices nori) 0) 
 	(=(number-executedDObIOb-roll it shape) 0) 
 	(=(number-executedDObIOb-slice rolls pieces) 0) 
 	(=(number-executedDObIOb-put them board) 0) 
 	(=(number-executedDObIOb-mix spoon spoon) 0) 
 	(=(number-executedDObIOb-repeat sheets sheets) 0) 
 	(=(number-executedIOb-boil rice) 0) 
 	(=(number-executedIOb-cook ricet) 0) 
 	(=(number-executedIOb-add salt) 0) 
 	(=(number-executedIOb-whisk honey) 0) 
 	(=(number-executedIOb-whisk vinegar) 0) 
 	(=(number-executedIOb-wait minutes) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(serve-saliency) 1) 
 	(=(pour-saliency mixture rice) 1) 
 	(=(lay-saliency mat surface) 1) 
 	(=(sprinkle-saliency rice nori) 1) 
 	(=(sprinkle-saliency mixture rice) 1) 
 	(=(lay-saliency pieces nori) 1) 
 	(=(lay-saliency slices nori) 1) 
 	(=(roll-saliency it shape) 1) 
 	(=(slice-saliency rolls pieces) 1) 
 	(=(put-saliency them board) 1) 
 	(=(mix-saliency spoon spoon) 1) 
 	(=(repeat-saliency sheets sheets) 1) 
 	(=(boil-saliency rice) 1) 
 	(=(cook-saliency ricet) 1) 
 	(=(add-saliency salt) 1) 
 	(=(whisk-saliency honey) 1) 
 	(=(whisk-saliency vinegar) 1) 
 	(=(wait-saliency minutes) 1) 
 	(=(take-saliency bowl) 1) 
 	(property-with spoon) 
 	(property-on surface) 
 	(property-on mat) 
 	(property-poss your) 
 	(property-over nori) 
 	(property-over rice) 
 	(property-on nori) 
 	(property-of nori) 
 	(property-into shape) 
 	(property-with sheets) 
 	(property-into pieces) 
 	(property-on board) 
 	(property-small bowl) 
 	(property-wooden spoon) 
 	(property-separate bowl) 
 	(property-bamboo mat) 
 	(property-other sheets) 
 	(property-cutting board) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executedDObIOb-pour mixture rice) 1) 
 	(=(number-executedDObIOb-lay mat surface) 1) 
 	(=(number-executedDObIOb-sprinkle rice nori) 1) 
 	(=(number-executedDObIOb-sprinkle mixture rice) 1) 
 	(=(number-executedDObIOb-lay pieces nori) 1) 
 	(=(number-executedDObIOb-lay slices nori) 1) 
 	(=(number-executedDObIOb-roll it shape) 1) 
 	(=(number-executedDObIOb-slice rolls pieces) 1) 
 	(=(number-executedDObIOb-put them board) 1) 
 	(=(number-executedDObIOb-mix spoon spoon) 1) 
 	(=(number-executedDObIOb-repeat sheets sheets) 1) 
 	(=(number-executedIOb-boil rice) 1) 
 	(=(number-executedIOb-cook ricet) 1) 
 	(=(number-executedIOb-add salt) 1) 
 	(=(number-executedIOb-whisk honey) 1) 
 	(=(number-executedIOb-whisk vinegar) 1) 
 	(=(number-executedIOb-wait minutes) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(finished)
)) 
 
)