(define (problem 2ndex_lobstersushi2) 
 
 (:domain 2ndex_lobstersushi2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-mix) 
 	(executed-slice cucumber half) 
 	(executed-cut slices slices) 
 	(executed-thaw tails) 
 	(executed-squeeze water) 
 	(executed-peel avocado) 
 	(executed-add mayo) 
 	(executed-cut ways) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-plate) 0) 
 	(=(number-executed-mix) 0) 
 	(=(number-executed-if) 0) 
 	(=(number-executed-capelin) 0) 
 	(=(number-executedDObIOb-chop tails cubes) 0) 
 	(=(number-executedDObIOb-slice cucumber half) 0) 
 	(=(number-executedDObIOb-fill bowl water) 0) 
 	(=(number-executedDObIOb-place mixture center) 0) 
 	(=(number-executedDObIOb-dip finger bowl) 0) 
 	(=(number-executedDObIOb-keep fillings place) 0) 
 	(=(number-executedDObIOb-roll it cylinder) 0) 
 	(=(number-executedDObIOb-place bowl bowl) 0) 
 	(=(number-executedDObIOb-cucumber half half) 0) 
 	(=(number-executedDObIOb-cut slices slices) 0) 
 	(=(number-executedDObIOb-wwet edge edge) 0) 
 	(=(number-executedDObIOb-roll pieces pieces) 0) 
 	(=(number-executedIOb-thaw tails) 0) 
 	(=(number-executedIOb-squeeze water) 0) 
 	(=(number-executedIOb-take half) 0) 
 	(=(number-executedIOb-cut ways) 0) 
 	(=(number-executedIOb-peel avocado) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(number-executedIOb-add mayo) 0) 
 	(=(number-executedIOb-take paper) 0) 
 	(=(number-executedIOb-place it) 0) 
 	(=(number-executedIOb-place cucumber) 0) 
 	(=(number-executedIOb-place avocado) 0) 
 	(property-into cubes) 
 	(property-into bowl) 
 	(property-in half) 
 	(property-to half) 
 	(property-into slices) 
 	(property-with water) 
 	(property-across center) 
 	(property-in bowl) 
 	(property-of water) 
 	(property-across edge) 
 	(property-of paper) 
 	(property-in place) 
 	(property-with fingers) 
 	(property-into cylinder) 
 	(property-into pieces) 
 	(property-with sauce) 
 	(property-with wasabi) 
 	(property-excess water) 
 	(property-long ways) 
 	(property-long slices) 
 	(property-mixing bowl) 
 	(property-langostine tails) 
 	(property-small bowl) 
 	(property-farthest edge) 
 	(property-closest paper) 
 	(property-tight cylinder) 
 	(property-frozen thaw) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-plate) 1) 
 	(=(number-executed-mix) 1) 
 	(=(number-executed-if) 1) 
 	(=(number-executed-capelin) 1) 
 	(=(number-executedDObIOb-chop tails cubes) 1) 
 	(=(number-executedDObIOb-slice cucumber half) 1) 
 	(=(number-executedDObIOb-fill bowl water) 1) 
 	(=(number-executedDObIOb-place mixture center) 1) 
 	(=(number-executedDObIOb-dip finger bowl) 1) 
 	(=(number-executedDObIOb-keep fillings place) 1) 
 	(=(number-executedDObIOb-roll it cylinder) 1) 
 	(=(number-executedDObIOb-place bowl bowl) 1) 
 	(=(number-executedDObIOb-cucumber half half) 1) 
 	(=(number-executedDObIOb-cut slices slices) 1) 
 	(=(number-executedDObIOb-wwet edge edge) 1) 
 	(=(number-executedDObIOb-roll pieces pieces) 1) 
 	(=(number-executedIOb-thaw tails) 1) 
 	(=(number-executedIOb-squeeze water) 1) 
 	(=(number-executedIOb-take half) 1) 
 	(=(number-executedIOb-cut ways) 1) 
 	(=(number-executedIOb-peel avocado) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(=(number-executedIOb-add mayo) 1) 
 	(=(number-executedIOb-take paper) 1) 
 	(=(number-executedIOb-place it) 1) 
 	(=(number-executedIOb-place cucumber) 1) 
 	(=(number-executedIOb-place avocado) 1) 
 	(finished)
)) 
 
)