(define (problem 2ndex_oatmealcookies) 
 
 (:domain 2ndex_oatmealcookies) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-preheat oven f) 
 	(executed-stir raisins raisins) 
 	(executed-scoop cookies) 
 	(=(number-executed-mix) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-place butter bowl) 0) 
 	(=(number-executedDObIOb-place sugar bowl) 0) 
 	(=(number-executedDObIOb-add ingredients ingredients) 0) 
 	(=(number-executedDObIOb-place them oven) 0) 
 	(=(number-executedDObIOb-stir raisins raisins) 0) 
 	(=(number-executedDObIOb-bake minutes minutes) 0) 
 	(=(number-executedIOb-beat butter) 0) 
 	(=(number-executedIOb-beat sugar) 0) 
 	(=(number-executedIOb-add eggs) 0) 
 	(=(number-executedIOb-add vanilla) 0) 
 	(=(number-executedIOb-scoop cookies) 0) 
 	(=(number-executedIOb-bake cookies) 0) 
 	(property-to f) 
 	(property-in bowl) 
 	(property-to ingredients) 
 	(property-in raisins) 
 	(property-in oven) 
 	(property-for minutes) 
 	(property-white sugar) 
 	(property-brown sugar) 
 	(property-large bowl) 
 	(property-dry ingredients) 
 	(property-wet ingredients) 
 	(property-preheated oven) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-mix) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-place butter bowl) 1) 
 	(=(number-executedDObIOb-place sugar bowl) 1) 
 	(=(number-executedDObIOb-add ingredients ingredients) 1) 
 	(=(number-executedDObIOb-place them oven) 1) 
 	(=(number-executedDObIOb-stir raisins raisins) 1) 
 	(=(number-executedDObIOb-bake minutes minutes) 1) 
 	(=(number-executedIOb-beat butter) 1) 
 	(=(number-executedIOb-beat sugar) 1) 
 	(=(number-executedIOb-add eggs) 1) 
 	(=(number-executedIOb-add vanilla) 1) 
 	(=(number-executedIOb-scoop cookies) 1) 
 	(=(number-executedIOb-bake cookies) 1) 
 	(finished)
)) 
 
)