(define (problem 2ndex_BananaFrenchtoast_3) 
 
 (:domain 2ndex_BananaFrenchtoast_3) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-set) 
 	(executed-divide slices bread) 
 	(executed-dip sandwiches mixture) 
 	(executed-dredge mixture mixture) 
 	(executed-press coat coat) 
 	(executed-melt butter skillet) 
 	(executed-put oven heat) 
 	(executed-add sandwiches skillet) 
 	(executed-cook crispy crispy) 
 	(executed-take bowl) 
 	(=(number-executed-slices) 0) 
 	(=(number-executed-set) 0) 
 	(=(number-executed-serve) 0) 
 	(=(number-executedDObIOb-divide slices bread) 0) 
 	(=(number-executedDObIOb-dip sandwiches mixture) 0) 
 	(=(number-executedDObIOb-melt butter skillet) 0) 
 	(=(number-executedDObIOb-put oven heat) 0) 
 	(=(number-executedDObIOb-add sandwiches skillet) 0) 
 	(=(number-executedDObIOb-dredge mixture mixture) 0) 
 	(=(number-executedDObIOb-press coat coat) 0) 
 	(=(number-executedDObIOb-cook crispy crispy) 0) 
 	(=(number-executedIOb-top bread) 0) 
 	(=(number-executedIOb-combine cornflakes) 0) 
 	(=(number-executedIOb-combine pecans) 0) 
 	(=(number-executedIOb-make coating) 0) 
 	(=(number-executedIOb-make sandwiches) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(number-executedIOb-whisk eggs) 0) 
 	(=(number-executedIOb-whisk milk) 0) 
 	(=(number-executedIOb-whisk vanilla) 0) 
 	(=(number-executedIOb-whisk cinnamon) 0) 
 	(=(number-executedIOb-whisk nutmeg) 0) 
 	(=(slices-saliency) 1) 
 	(=(set-saliency) 1) 
 	(=(serve-saliency) 1) 
 	(=(divide-saliency slices bread) 1) 
 	(=(dip-saliency sandwiches mixture) 1) 
 	(=(melt-saliency butter skillet) 1) 
 	(=(put-saliency oven heat) 1) 
 	(=(add-saliency sandwiches skillet) 1) 
 	(=(dredge-saliency mixture mixture) 1) 
 	(=(press-saliency coat coat) 1) 
 	(=(cook-saliency crispy crispy) 1) 
 	(=(top-saliency bread) 1) 
 	(=(combine-saliency cornflakes) 1) 
 	(=(combine-saliency pecans) 1) 
 	(=(make-saliency coating) 1) 
 	(=(make-saliency sandwiches) 1) 
 	(=(take-saliency bowl) 1) 
 	(=(whisk-saliency eggs) 1) 
 	(=(whisk-saliency milk) 1) 
 	(=(whisk-saliency vanilla) 1) 
 	(=(whisk-saliency cinnamon) 1) 
 	(=(whisk-saliency nutmeg) 1) 
 	(property-among bread) 
 	(property-with bread) 
 	(property-into mixture) 
 	(property-in mixture) 
 	(property-to coat) 
 	(property-in skillet) 
 	(property-on heat) 
 	(property-to skillet) 
 	(property-as crispy) 
 	(property-remaining bread) 
 	(property-large bowl) 
 	(property-large skillet) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-slices) 1) 
 	(=(number-executed-set) 1) 
 	(=(number-executed-serve) 1) 
 	(=(number-executedDObIOb-divide slices bread) 1) 
 	(=(number-executedDObIOb-dip sandwiches mixture) 1) 
 	(=(number-executedDObIOb-melt butter skillet) 1) 
 	(=(number-executedDObIOb-put oven heat) 1) 
 	(=(number-executedDObIOb-add sandwiches skillet) 1) 
 	(=(number-executedDObIOb-dredge mixture mixture) 1) 
 	(=(number-executedDObIOb-press coat coat) 1) 
 	(=(number-executedDObIOb-cook crispy crispy) 1) 
 	(=(number-executedIOb-top bread) 1) 
 	(=(number-executedIOb-combine cornflakes) 1) 
 	(=(number-executedIOb-combine pecans) 1) 
 	(=(number-executedIOb-make coating) 1) 
 	(=(number-executedIOb-make sandwiches) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(=(number-executedIOb-whisk eggs) 1) 
 	(=(number-executedIOb-whisk milk) 1) 
 	(=(number-executedIOb-whisk vanilla) 1) 
 	(=(number-executedIOb-whisk cinnamon) 1) 
 	(=(number-executedIOb-whisk nutmeg) 1) 
 	(finished)
)) 
 
)