(define (problem 2ndex_buttercookie) 
 
 (:domain 2ndex_buttercookie) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-roll) 
 	(executed-preheat oven c) 
 	(executed-mix ingredients batter) 
 	(executed-place bowl fridge) 
 	(executed-place them tray) 
 	(executed-cut log slices) 
 	(executed-cream butter) 
 	(executed-cream sugar) 
 	(executed-use press) 
 	(=(number-executed-roll) 0) 
 	(=(number-executed-make) 0) 
 	(=(number-executed-finished) 0) 
 	(=(number-executedDObIOb-preheat oven c) 0) 
 	(=(number-executedDObIOb-stir egg mixture) 0) 
 	(=(number-executedDObIOb-stir vanilla mixture) 0) 
 	(=(number-executedDObIOb-stir salt bowl) 0) 
 	(=(number-executedDObIOb-stir flour bowl) 0) 
 	(=(number-executedDObIOb-mix ingredients batter) 0) 
 	(=(number-executedDObIOb-place bowl fridge) 0) 
 	(=(number-executedDObIOb-cut log slices) 0) 
 	(=(number-executedDObIOb-place them tray) 0) 
 	(=(number-executedDObIOb-cook cookies minutes) 0) 
 	(=(number-executedDObIOb-put bowl bowl) 0) 
 	(=(number-executedIOb-cream butter) 0) 
 	(=(number-executedIOb-cream sugar) 0) 
 	(=(number-executedIOb-use press) 0) 
 	(property-to c) 
 	(property-of butter) 
 	(property-of sugar) 
 	(property-into bowl) 
 	(property-into mixture) 
 	(property-in bowl) 
 	(property-into batter) 
 	(property-of dough) 
 	(property-in fridge) 
 	(property-into slices) 
 	(property-onto tray) 
 	(property-for minutes) 
 	(property-mixing bowl) 
 	(property-separate bowl) 
 	(property-baking tray) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-roll) 1) 
 	(=(number-executed-make) 1) 
 	(=(number-executed-finished) 1) 
 	(=(number-executedDObIOb-preheat oven c) 1) 
 	(=(number-executedDObIOb-stir egg mixture) 1) 
 	(=(number-executedDObIOb-stir vanilla mixture) 1) 
 	(=(number-executedDObIOb-stir salt bowl) 1) 
 	(=(number-executedDObIOb-stir flour bowl) 1) 
 	(=(number-executedDObIOb-mix ingredients batter) 1) 
 	(=(number-executedDObIOb-place bowl fridge) 1) 
 	(=(number-executedDObIOb-cut log slices) 1) 
 	(=(number-executedDObIOb-place them tray) 1) 
 	(=(number-executedDObIOb-cook cookies minutes) 1) 
 	(=(number-executedDObIOb-put bowl bowl) 1) 
 	(=(number-executedIOb-cream butter) 1) 
 	(=(number-executedIOb-cream sugar) 1) 
 	(=(number-executedIOb-use press) 1) 
 	(finished)
)) 
 
)