(define (problem 2ndex_ChocolateCookies3) 
 
 (:domain 2ndex_ChocolateCookies3) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-preheat oven f) 
 	(executed-put them bowl) 
 	(executed-mix fork fork) 
 	(executed-add mixture center) 
 	(executed-bake minutes minutes) 
 	(executed-measure ingredients) 
 	(executed-take cookie) 
 	(=(number-executed-finish) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-put them bowl) 0) 
 	(=(number-executedDObIOb-add mixture center) 0) 
 	(=(number-executedDObIOb-mix fork fork) 0) 
 	(=(number-executedDObIOb-bake minutes minutes) 0) 
 	(=(number-executedDObIOb-cool plate plate) 0) 
 	(=(number-executedIOb-measure ingredients) 0) 
 	(=(number-executedIOb-take cookie) 0) 
 	(property-to f) 
 	(property-in bowl) 
 	(property-with fork) 
 	(property-to center) 
 	(property-for minutes) 
 	(property-on plate) 
 	(property-small bowl) 
 	(property-pre cookie) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-finish) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-put them bowl) 1) 
 	(=(number-executedDObIOb-add mixture center) 1) 
 	(=(number-executedDObIOb-mix fork fork) 1) 
 	(=(number-executedDObIOb-bake minutes minutes) 1) 
 	(=(number-executedDObIOb-cool plate plate) 1) 
 	(=(number-executedIOb-measure ingredients) 1) 
 	(=(number-executedIOb-take cookie) 1) 
 	(finished)
)) 
 
)