(define (problem 2ndex_friedFrenchToast_2) 
 
 (:domain 2ndex_friedFrenchToast_2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-heat) 
 	(executed-soak breads mixture) 
 	(executed-put them) 
 	(executed-wipe egg) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-heat) 0) 
 	(=(number-executedDObIOb-soak breads mixture) 0) 
 	(=(number-executedDObIOb-whisk milk milk) 0) 
 	(=(number-executedDObIOb-oil fryer fryer) 0) 
 	(=(number-executedDObIOb-fryer f f) 0) 
 	(=(number-executedDObIOb-cook deepfryer deepfryer) 0) 
 	(=(number-executedIOb-whisk milk) 0) 
 	(=(number-executedIOb-cook deepfryer) 0) 
 	(=(number-executedIOb-beat eggs) 0) 
 	(=(number-executedIOb-beat sugar) 0) 
 	(=(number-executedIOb-beat salt) 0) 
 	(=(number-executedIOb-put them) 0) 
 	(=(number-executedIOb-mixing bowl) 0) 
 	(=(number-executedIOb-whisk flour) 0) 
 	(=(number-executedIOb-wipe egg) 0) 
 	(=(number-executedIOb-cook minutes) 0) 
 	(property-in milk) 
 	(property-in fryer) 
 	(property-to f) 
 	(property-in mixture) 
 	(property-in deepfryer) 
 	(property- ) 
 	(property-on plate) 
 	(property-excess egg) 
 	(property-french toast) 
 	(property-mixing put) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-heat) 1) 
 	(=(number-executedDObIOb-soak breads mixture) 1) 
 	(=(number-executedDObIOb-whisk milk milk) 1) 
 	(=(number-executedDObIOb-oil fryer fryer) 1) 
 	(=(number-executedDObIOb-fryer f f) 1) 
 	(=(number-executedDObIOb-cook deepfryer deepfryer) 1) 
 	(=(number-executedIOb-whisk milk) 1) 
 	(=(number-executedIOb-cook deepfryer) 1) 
 	(=(number-executedIOb-beat eggs) 1) 
 	(=(number-executedIOb-beat sugar) 1) 
 	(=(number-executedIOb-beat salt) 1) 
 	(=(number-executedIOb-put them) 1) 
 	(=(number-executedIOb-mixing bowl) 1) 
 	(=(number-executedIOb-whisk flour) 1) 
 	(=(number-executedIOb-wipe egg) 1) 
 	(=(number-executedIOb-cook minutes) 1) 
 	(finished)
)) 
 
)