(define (problem 2ndex_baconsushi) 
 
 (:domain 2ndex_baconsushi) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-boil rice pot) 
 	(executed-cover mat wrap) 
 	(executed-roll sushi shape) 
 	(executed-uncover rice) 
 	(executed-spread rice) 
 	(executed-roll cheese) 
 	(=(number-executed-veins) 0) 
 	(=(number-executed-set) 0) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-seeds) 0) 
 	(=(number-executedDObIOb-boil rice pot) 0) 
 	(=(number-executedDObIOb-cool rice bowl) 0) 
 	(=(number-executedDObIOb-slice it strips) 0) 
 	(=(number-executedDObIOb-cover mat wrap) 0) 
 	(=(number-executedDObIOb-roll sushi shape) 0) 
 	(=(number-executedDObIOb-slice sushi pieces) 0) 
 	(=(number-executedIOb-uncover rice) 0) 
 	(=(number-executedIOb-sprinkle vinegar) 0) 
 	(=(number-executedIOb-sprinkle sugar) 0) 
 	(=(number-executedIOb-sprinkle salt) 0) 
 	(=(number-executedIOb-prepare jalapeño) 0) 
 	(=(number-executedIOb-remove stem) 0) 
 	(=(number-executedIOb-prepare cucumber) 0) 
 	(=(number-executedIOb-prepare avocado) 0) 
 	(=(number-executedIOb-roll cheese) 0) 
 	(=(number-executedIOb-spread rice) 0) 
 	(=(number-executedIOb-arrange cheese) 0) 
 	(property-in pot) 
 	(property-in bowl) 
 	(property-into strips) 
 	(property-with wrap) 
 	(property-of sheet) 
 	(property-into shape) 
 	(property-into pieces) 
 	(property-large pot) 
 	(property-large bowl) 
 	(property-plastic wrap) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-veins) 1) 
 	(=(number-executed-set) 1) 
 	(=(number-executed-serve) 1) 
 	(=(number-executed-seeds) 1) 
 	(=(number-executedDObIOb-boil rice pot) 1) 
 	(=(number-executedDObIOb-cool rice bowl) 1) 
 	(=(number-executedDObIOb-slice it strips) 1) 
 	(=(number-executedDObIOb-cover mat wrap) 1) 
 	(=(number-executedDObIOb-roll sushi shape) 1) 
 	(=(number-executedDObIOb-slice sushi pieces) 1) 
 	(=(number-executedIOb-uncover rice) 1) 
 	(=(number-executedIOb-sprinkle vinegar) 1) 
 	(=(number-executedIOb-sprinkle sugar) 1) 
 	(=(number-executedIOb-sprinkle salt) 1) 
 	(=(number-executedIOb-prepare jalapeño) 1) 
 	(=(number-executedIOb-remove stem) 1) 
 	(=(number-executedIOb-prepare cucumber) 1) 
 	(=(number-executedIOb-prepare avocado) 1) 
 	(=(number-executedIOb-roll cheese) 1) 
 	(=(number-executedIOb-spread rice) 1) 
 	(=(number-executedIOb-arrange cheese) 1) 
 	(finished)
)) 
 
)