(define (problem 2ndex_peanutbuttercookies) 
 
 (:domain 2ndex_peanutbuttercookies) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-place them saucepan) 
 	(executed-put saucepan stove) 
 	(executed-stir oatmeal oatmeal) 
 	(executed-scoop cookies sheet) 
 	(executed-boil milk) 
 	(executed-boil sugar) 
 	(=(number-executed-finished) 0) 
 	(=(number-executedDObIOb-place them saucepan) 0) 
 	(=(number-executedDObIOb-put saucepan stove) 0) 
 	(=(number-executedDObIOb-turn burner medium) 0) 
 	(=(number-executedDObIOb-scoop cookies sheet) 0) 
 	(=(number-executedDObIOb-stir oatmeal oatmeal) 0) 
 	(=(number-executedDObIOb-cool minutes minutes) 0) 
 	(=(number-executedIOb-boil milk) 0) 
 	(=(number-executedIOb-boil sugar) 0) 
 	(=(number-executedIOb-add vanilla) 0) 
 	(=(number-executedIOb-add butter) 0) 
 	(=(number-executedIOb-add salt) 0) 
 	(=(finished-saliency) 1) 
 	(=(place-saliency them saucepan) 1) 
 	(=(put-saliency saucepan stove) 1) 
 	(=(turn-saliency burner medium) 1) 
 	(=(scoop-saliency cookies sheet) 1) 
 	(=(stir-saliency oatmeal oatmeal) 1) 
 	(=(cool-saliency minutes minutes) 1) 
 	(=(boil-saliency milk) 1) 
 	(=(boil-saliency sugar) 1) 
 	(=(add-saliency vanilla) 1) 
 	(=(add-saliency butter) 1) 
 	(=(add-saliency salt) 1) 
 	(property-in saucepan) 
 	(property-on stove) 
 	(property-to medium) 
 	(property-in oatmeal) 
 	(property-onto sheet) 
 	(property-for minutes) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-finished) 1) 
 	(=(number-executedDObIOb-place them saucepan) 1) 
 	(=(number-executedDObIOb-put saucepan stove) 1) 
 	(=(number-executedDObIOb-turn burner medium) 1) 
 	(=(number-executedDObIOb-scoop cookies sheet) 1) 
 	(=(number-executedDObIOb-stir oatmeal oatmeal) 1) 
 	(=(number-executedDObIOb-cool minutes minutes) 1) 
 	(=(number-executedIOb-boil milk) 1) 
 	(=(number-executedIOb-boil sugar) 1) 
 	(=(number-executedIOb-add vanilla) 1) 
 	(=(number-executedIOb-add butter) 1) 
 	(=(number-executedIOb-add salt) 1) 
 	(finished)
)) 
 
)