(define (problem 2ndex_sushi3) 
 
 (:domain 2ndex_sushi3) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-boil) 
 	(executed-cook) 
 	(executed-cover) 
 	(executed-stir) 
 	(executed-fold it rectangle) 
 	(executed-cool fridge fridge) 
 	(executed-chop them pieces) 
 	(executed-reduce heat) 
 	(executed-wait minutes) 
 	(executed-prep veggies) 
 	(=(number-executed-sugar) 0) 
 	(=(number-executed-stir) 0) 
 	(=(number-executed-start) 0) 
 	(=(number-executed-set) 0) 
 	(=(number-executed-saucepand) 0) 
 	(=(number-executed-pat) 0) 
 	(=(number-executed-cover) 0) 
 	(=(number-executed-cook) 0) 
 	(=(number-executed-boil) 0) 
 	(=(number-executedDObIOb-rinse rice strainer) 0) 
 	(=(number-executedDObIOb-add salt saucepan) 0) 
 	(=(number-executedDObIOb-chop them pieces) 0) 
 	(=(number-executedDObIOb-fold it rectangle) 0) 
 	(=(number-executedDObIOb-place it surface) 0) 
 	(=(number-executedDObIOb-add rice fingers) 0) 
 	(=(number-executedDObIOb-add saucepan water) 0) 
 	(=(number-executedDObIOb-heat heat heat) 0) 
 	(=(number-executedDObIOb-place jar jar) 0) 
 	(=(number-executedDObIOb-cool fridge fridge) 0) 
 	(=(number-executedDObIOb-top wrap wrap) 0) 
 	(=(number-executedDObIOb-top nori sheet) 0) 
 	(=(number-executedDObIOb-layer rice rice) 0) 
 	(=(number-executedDObIOb-all nori nori) 0) 
 	(=(number-executedDObIOb-slice knife knife) 0) 
 	(=(number-executedDObIOb-serve pickle pickle) 0) 
 	(=(number-executedIOb-top wrap) 0) 
 	(=(number-executedIOb-reduce heat) 0) 
 	(=(number-executedIOb-wait minutes) 0) 
 	(=(number-executedIOb-add vinegar) 0) 
 	(=(number-executedIOb-kill heat) 0) 
 	(=(number-executedIOb-add mixture) 0) 
 	(=(number-executedIOb-prep veggies) 0) 
 	(=(number-executedIOb-grab towel) 0) 
 	(=(number-executedIOb-use hands) 0) 
 	(=(number-executedIOb-roll nori) 0) 
 	(=(sugar-saliency) 1) 
 	(=(stir-saliency) 1) 
 	(=(start-saliency) 1) 
 	(=(set-saliency) 1) 
 	(=(saucepand-saliency) 1) 
 	(=(pat-saliency) 1) 
 	(=(cover-saliency) 1) 
 	(=(cook-saliency) 1) 
 	(=(boil-saliency) 1) 
 	(=(rinse-saliency rice strainer) 1) 
 	(=(add-saliency salt saucepan) 1) 
 	(=(chop-saliency them pieces) 1) 
 	(=(fold-saliency it rectangle) 1) 
 	(=(place-saliency it surface) 1) 
 	(=(add-saliency rice fingers) 1) 
 	(=(add-saliency saucepan water) 1) 
 	(=(heat-saliency heat heat) 1) 
 	(=(place-saliency jar jar) 1) 
 	(=(cool-saliency fridge fridge) 1) 
 	(=(top-saliency wrap wrap) 1) 
 	(=(top-saliency nori sheet) 1) 
 	(=(layer-saliency rice rice) 1) 
 	(=(all-saliency nori nori) 1) 
 	(=(slice-saliency knife knife) 1) 
 	(=(serve-saliency pickle pickle) 1) 
 	(=(top-saliency wrap) 1) 
 	(=(reduce-saliency heat) 1) 
 	(=(wait-saliency minutes) 1) 
 	(=(add-saliency vinegar) 1) 
 	(=(kill-saliency heat) 1) 
 	(=(add-saliency mixture) 1) 
 	(=(prep-saliency veggies) 1) 
 	(=(grab-saliency towel) 1) 
 	(=(use-saliency hands) 1) 
 	(=(roll-saliency nori) 1) 
 	(property-in strainer) 
 	(property-with water) 
 	(property-to saucepan) 
 	(property-over heat) 
 	(property-in jar) 
 	(property-in fridge) 
 	(property-into pieces) 
 	(property-into rectangle) 
 	(property-on surface) 
 	(property-with wrap) 
 	(property-of nori) 
 	(property-with sheet) 
 	(property-of rice) 
 	(property-over nori) 
 	(property-of veggies) 
 	(property-poss your) 
 	(property-with fingers) 
 	(property-over towel) 
 	(property-over wrap) 
 	(property-with knife) 
 	(property-with pickle) 
 	(property-fine strainer) 
 	(property-small saucepan) 
 	(property-cooled mixture) 
 	(property-thin pieces) 
 	(property-thick towel) 
 	(property-flat surface) 
 	(property-wet hands) 
 	(property-thin layer) 
 	(property-plastic wrap) 
 	(property-sharp knife) 
 	(property-low reduce) 
 	(property-done kill) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-sugar) 1) 
 	(=(number-executed-stir) 1) 
 	(=(number-executed-start) 1) 
 	(=(number-executed-set) 1) 
 	(=(number-executed-saucepand) 1) 
 	(=(number-executed-pat) 1) 
 	(=(number-executed-cover) 1) 
 	(=(number-executed-cook) 1) 
 	(=(number-executed-boil) 1) 
 	(=(number-executedDObIOb-rinse rice strainer) 1) 
 	(=(number-executedDObIOb-add salt saucepan) 1) 
 	(=(number-executedDObIOb-chop them pieces) 1) 
 	(=(number-executedDObIOb-fold it rectangle) 1) 
 	(=(number-executedDObIOb-place it surface) 1) 
 	(=(number-executedDObIOb-add rice fingers) 1) 
 	(=(number-executedDObIOb-add saucepan water) 1) 
 	(=(number-executedDObIOb-heat heat heat) 1) 
 	(=(number-executedDObIOb-place jar jar) 1) 
 	(=(number-executedDObIOb-cool fridge fridge) 1) 
 	(=(number-executedDObIOb-top wrap wrap) 1) 
 	(=(number-executedDObIOb-top nori sheet) 1) 
 	(=(number-executedDObIOb-layer rice rice) 1) 
 	(=(number-executedDObIOb-all nori nori) 1) 
 	(=(number-executedDObIOb-slice knife knife) 1) 
 	(=(number-executedDObIOb-serve pickle pickle) 1) 
 	(=(number-executedIOb-top wrap) 1) 
 	(=(number-executedIOb-reduce heat) 1) 
 	(=(number-executedIOb-wait minutes) 1) 
 	(=(number-executedIOb-add vinegar) 1) 
 	(=(number-executedIOb-kill heat) 1) 
 	(=(number-executedIOb-add mixture) 1) 
 	(=(number-executedIOb-prep veggies) 1) 
 	(=(number-executedIOb-grab towel) 1) 
 	(=(number-executedIOb-use hands) 1) 
 	(=(number-executedIOb-roll nori) 1) 
 	(finished)
)) 
 
)