(define (problem 2ndex_mountainvacation) 
 
 (:domain 2ndex_mountainvacation) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-need) 
 	(executed-relax) 
 	(executed-place days days) 
 	(executed-stay one one) 
 	(executed-offer what) 
 	(executed-pack gear) 
 	(executed-meet locals) 
 	(=(number-executed-relax) 0) 
 	(=(number-executed-need) 0) 
 	(=(number-executed-enjoy) 0) 
 	(=(number-executedDObIOb-stay one one) 0) 
 	(=(number-executedDObIOb-place days days) 0) 
 	(=(number-executedIOb-offer what) 0) 
 	(=(number-executedIOb-pack gear) 0) 
 	(=(number-executedIOb-meet locals) 0) 
 	(=(relax-saliency) 1) 
 	(=(need-saliency) 1) 
 	(=(enjoy-saliency) 1) 
 	(=(stay-saliency one one) 1) 
 	(=(place-saliency days days) 1) 
 	(=(offer-saliency what) 1) 
 	(=(pack-saliency gear) 1) 
 	(=(meet-saliency locals) 1) 
 	(property-of location) 
 	(property-of season) 
 	(property-poss your) 
 	(property-in one) 
 	(property-for days) 
 	(property-few days) 
 	(property-possible days) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-relax) 1) 
 	(=(number-executed-need) 1) 
 	(=(number-executed-enjoy) 1) 
 	(=(number-executedDObIOb-stay one one) 1) 
 	(=(number-executedDObIOb-place days days) 1) 
 	(=(number-executedIOb-offer what) 1) 
 	(=(number-executedIOb-pack gear) 1) 
 	(=(number-executedIOb-meet locals) 1) 
 	(finished)
)) 
 
)