(define (problem 2ndex_ChocolateCookies4) 
 
 (:domain 2ndex_ChocolateCookies4) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-preheat oven f) 
 	(executed-spoon flour cup) 
 	(executed-drop tablespoonfuls sheets) 
 	(executed-fold cherries) 
 	(executed-fold chips) 
 	(=(number-executed-serve) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-spoon flour cup) 0) 
 	(=(number-executedDObIOb-place sugar bowl) 0) 
 	(=(number-executedDObIOb-place butter bowl) 0) 
 	(=(number-executedDObIOb-level knife knife) 0) 
 	(=(number-executedDObIOb-stir whisk whisk) 0) 
 	(=(number-executedDObIOb-beat mixer mixer) 0) 
 	(=(number-executedDObIOb-drop tablespoonfuls sheets) 0) 
 	(=(number-executedDObIOb-bake f f) 0) 
 	(=(number-executedDObIOb-remove oven oven) 0) 
 	(=(number-executedDObIOb-cool pans pans) 0) 
 	(=(number-executedDObIOb-wait minutes minutes) 0) 
 	(=(number-executedDObIOb-cool racks racks) 0) 
 	(=(number-executedIOb-combine flour) 0) 
 	(=(number-executedIOb-combine cocoa) 0) 
 	(=(number-executedIOb-combine powder) 0) 
 	(=(number-executedIOb-combine soda) 0) 
 	(=(number-executedIOb-combine salt) 0) 
 	(=(number-executedIOb-add vanilla) 0) 
 	(=(number-executedIOb-add eggs) 0) 
 	(=(number-executedIOb-flour mixture) 0) 
 	(=(number-executedIOb-fold cherries) 0) 
 	(=(number-executedIOb-fold chips) 0) 
 	(=(number-executedIOb-wait minutes) 0) 
 	(property-to f) 
 	(property-into cup) 
 	(property-with knife) 
 	(property-with whisk) 
 	(property-in bowl) 
 	(property-with mixer) 
 	(property-by tablespoonfuls) 
 	(property-onto sheets) 
 	(property-at f) 
 	(property-from oven) 
 	(property-on pans) 
 	(property-for minutes) 
 	(property-on racks) 
 	(property-baking powder) 
 	(property-baking soda) 
 	(property-baking sheets) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-spoon flour cup) 1) 
 	(=(number-executedDObIOb-place sugar bowl) 1) 
 	(=(number-executedDObIOb-place butter bowl) 1) 
 	(=(number-executedDObIOb-level knife knife) 1) 
 	(=(number-executedDObIOb-stir whisk whisk) 1) 
 	(=(number-executedDObIOb-beat mixer mixer) 1) 
 	(=(number-executedDObIOb-drop tablespoonfuls sheets) 1) 
 	(=(number-executedDObIOb-bake f f) 1) 
 	(=(number-executedDObIOb-remove oven oven) 1) 
 	(=(number-executedDObIOb-cool pans pans) 1) 
 	(=(number-executedDObIOb-wait minutes minutes) 1) 
 	(=(number-executedDObIOb-cool racks racks) 1) 
 	(=(number-executedIOb-combine flour) 1) 
 	(=(number-executedIOb-combine cocoa) 1) 
 	(=(number-executedIOb-combine powder) 1) 
 	(=(number-executedIOb-combine soda) 1) 
 	(=(number-executedIOb-combine salt) 1) 
 	(=(number-executedIOb-add vanilla) 1) 
 	(=(number-executedIOb-add eggs) 1) 
 	(=(number-executedIOb-flour mixture) 1) 
 	(=(number-executedIOb-fold cherries) 1) 
 	(=(number-executedIOb-fold chips) 1) 
 	(=(number-executedIOb-wait minutes) 1) 
 	(finished)
)) 
 
)