(define (problem 2ndex_BananaFrenchtoast_2) 
 
 (:domain 2ndex_BananaFrenchtoast_2) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-mash banana dish) 
 	(executed-serve syrup syrup) 
 	(executed-add milk) 
 	(executed-add spices) 
 	(executed-give stir) 
 	(=(number-executed-finished) 0) 
 	(=(number-executedDObIOb-mash banana dish) 0) 
 	(=(number-executedDObIOb-dip breads mixture) 0) 
 	(=(number-executedDObIOb-repeat side side) 0) 
 	(=(number-executedDObIOb-serve syrup syrup) 0) 
 	(=(number-executedIOb-add milk) 0) 
 	(=(number-executedIOb-add spices) 0) 
 	(=(number-executedIOb-give stir) 0) 
 	(=(finished-saliency) 1) 
 	(=(mash-saliency banana dish) 1) 
 	(=(dip-saliency breads mixture) 1) 
 	(=(repeat-saliency side side) 1) 
 	(=(serve-saliency syrup syrup) 1) 
 	(=(add-saliency milk) 1) 
 	(=(add-saliency spices) 1) 
 	(=(give-saliency stir) 1) 
 	(property-in dish) 
 	(property-in mixture) 
 	(property-on side) 
 	(property-on griddle) 
 	(property-per side) 
 	(property-with syrup) 
 	(property-good stir) 
 	(property-other side) 
 	(property-heated griddle) 
 	(property-pure syrup) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-finished) 1) 
 	(=(number-executedDObIOb-mash banana dish) 1) 
 	(=(number-executedDObIOb-dip breads mixture) 1) 
 	(=(number-executedDObIOb-repeat side side) 1) 
 	(=(number-executedDObIOb-serve syrup syrup) 1) 
 	(=(number-executedIOb-add milk) 1) 
 	(=(number-executedIOb-add spices) 1) 
 	(=(number-executedIOb-give stir) 1) 
 	(finished)
)) 
 
)