(define (problem 2ndex_seafoodsushi) 
 
 (:domain 2ndex_seafoodsushi) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-garnish) 
 	(executed-cut seafood slices) 
 	(executed-dip hands water) 
 	(executed-hold hand) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-repeat) 0) 
 	(=(number-executed-garnish) 0) 
 	(=(number-executedDObIOb-cut seafood slices) 0) 
 	(=(number-executedDObIOb-dip hands water) 0) 
 	(=(number-executedDObIOb-place wasabi side) 0) 
 	(=(number-executedDObIOb-place fish rice) 0) 
 	(=(number-executedDObIOb-put side rice) 0) 
 	(=(number-executedDObIOb-shape it rectangle) 0) 
 	(=(number-executedIOb-shape items) 0) 
 	(=(number-executedIOb-hold hand) 0) 
 	(=(number-executedIOb-press downwards) 0) 
 	(=(number-executedIOb-using salmon) 0) 
 	(=(number-executedIOb-using shrimp) 0) 
 	(=(serve-saliency) 1) 
 	(=(repeat-saliency) 1) 
 	(=(garnish-saliency) 1) 
 	(=(cut-saliency seafood slices) 1) 
 	(=(dip-saliency hands water) 1) 
 	(=(place-saliency wasabi side) 1) 
 	(=(place-saliency fish rice) 1) 
 	(=(put-saliency side rice) 1) 
 	(=(shape-saliency it rectangle) 1) 
 	(=(shape-saliency items) 1) 
 	(=(hold-saliency hand) 1) 
 	(=(press-saliency downwards) 1) 
 	(=(using-saliency salmon) 1) 
 	(=(using-saliency shrimp) 1) 
 	(property-into slices) 
 	(property-in water) 
 	(property-poss your) 
 	(property-of rice) 
 	(property-of slice) 
 	(property-on side) 
 	(property-on rice) 
 	(property-in rectangle) 
 	(property-small slices) 
 	(property-small amount) 
 	(property-wasabi side) 
 	(property-rounded rectangle) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-repeat) 1) 
 	(=(number-executed-garnish) 1) 
 	(=(number-executedDObIOb-cut seafood slices) 1) 
 	(=(number-executedDObIOb-dip hands water) 1) 
 	(=(number-executedDObIOb-place wasabi side) 1) 
 	(=(number-executedDObIOb-place fish rice) 1) 
 	(=(number-executedDObIOb-put side rice) 1) 
 	(=(number-executedDObIOb-shape it rectangle) 1) 
 	(=(number-executedIOb-shape items) 1) 
 	(=(number-executedIOb-hold hand) 1) 
 	(=(number-executedIOb-press downwards) 1) 
 	(=(number-executedIOb-using salmon) 1) 
 	(=(number-executedIOb-using shrimp) 1) 
 	(finished)
)) 
 
)