(define (problem 2ndex_fancyFrenchToast) 
 
 (:domain 2ndex_fancyFrenchToast) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-cut) 
 	(executed-mix) 
 	(executed-make) 
 	(executed-dip them mixture) 
 	(executed-soak minutes minutes) 
 	(executed-soak it mixture) 
 	(executed-transfer them sheet) 
 	(executed-take bread) 
 	(executed-take skillet) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-mix) 0) 
 	(=(number-executed-make) 0) 
 	(=(number-executed-cut) 0) 
 	(=(number-executedDObIOb-add eggs bowl) 0) 
 	(=(number-executedDObIOb-add milk eggs) 0) 
 	(=(number-executedDObIOb-soak it mixture) 0) 
 	(=(number-executedDObIOb-put it refrigerator) 0) 
 	(=(number-executedDObIOb-dip them mixture) 0) 
 	(=(number-executedDObIOb-put bread skillet) 0) 
 	(=(number-executedDObIOb-transfer them sheet) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-pieces bread bread) 0) 
 	(=(number-executedDObIOb-soak minutes minutes) 0) 
 	(=(number-executedDObIOb-minutes side side) 0) 
 	(=(number-executedIOb-add allspice) 0) 
 	(=(number-executedIOb-add cinnamon) 0) 
 	(=(number-executedIOb-take bread) 0) 
 	(=(number-executedIOb-take skillet) 0) 
 	(=(number-executedIOb-put heat) 0) 
 	(property-of bread) 
 	(property-into bowl) 
 	(property-to eggs) 
 	(property-of vanilla) 
 	(property-of salt) 
 	(property-in refrigerator) 
 	(property-in mixture) 
 	(property-of butter) 
 	(property-on skillet) 
 	(property-on side) 
 	(property-poss your) 
 	(property-to sheet) 
 	(property-to f) 
 	(property-for minutes) 
 	(property-thick pieces) 
 	(property-nice skillet) 
 	(property-large skillet) 
 	(property-whole butter) 
 	(property-baking sheet) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-mix) 1) 
 	(=(number-executed-make) 1) 
 	(=(number-executed-cut) 1) 
 	(=(number-executedDObIOb-add eggs bowl) 1) 
 	(=(number-executedDObIOb-add milk eggs) 1) 
 	(=(number-executedDObIOb-soak it mixture) 1) 
 	(=(number-executedDObIOb-put it refrigerator) 1) 
 	(=(number-executedDObIOb-dip them mixture) 1) 
 	(=(number-executedDObIOb-put bread skillet) 1) 
 	(=(number-executedDObIOb-transfer them sheet) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-pieces bread bread) 1) 
 	(=(number-executedDObIOb-soak minutes minutes) 1) 
 	(=(number-executedDObIOb-minutes side side) 1) 
 	(=(number-executedIOb-add allspice) 1) 
 	(=(number-executedIOb-add cinnamon) 1) 
 	(=(number-executedIOb-take bread) 1) 
 	(=(number-executedIOb-take skillet) 1) 
 	(=(number-executedIOb-put heat) 1) 
 	(finished)
)) 
 
)