(define (problem 2ndex_VeganFrenchtoast) 
 
 (:domain 2ndex_VeganFrenchtoast) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-heat) 
 	(executed-cool) 
 	(executed-put heat heat) 
 	(executed-dip bread mixture) 
 	(executed-remove toast pan) 
 	(executed-melt butter) 
 	(=(number-executed-shaved) 0) 
 	(=(number-executed-heat) 0) 
 	(=(number-executed-cool) 0) 
 	(=(number-executedDObIOb-dip bread mixture) 0) 
 	(=(number-executedDObIOb-place bread skillet) 0) 
 	(=(number-executedDObIOb-remove toast pan) 0) 
 	(=(number-executedDObIOb-put heat heat) 0) 
 	(=(number-executedDObIOb-place plate plate) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(number-executedIOb-mix milk) 0) 
 	(=(number-executedIOb-melt butter) 0) 
 	(property-on heat) 
 	(property-over heat) 
 	(property-into mixture) 
 	(property-into skillet) 
 	(property-from pan) 
 	(property-on plate) 
 	(property-large bowl) 
 	(property-hot skillet) 
 	(property-french toast) 
 	(property-fresh berries) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-shaved) 1) 
 	(=(number-executed-heat) 1) 
 	(=(number-executed-cool) 1) 
 	(=(number-executedDObIOb-dip bread mixture) 1) 
 	(=(number-executedDObIOb-place bread skillet) 1) 
 	(=(number-executedDObIOb-remove toast pan) 1) 
 	(=(number-executedDObIOb-put heat heat) 1) 
 	(=(number-executedDObIOb-place plate plate) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(=(number-executedIOb-mix milk) 1) 
 	(=(number-executedIOb-melt butter) 1) 
 	(finished)
)) 
 
)