(define (problem 2ndex_ovenfrenchtoast) 
 
 (:domain 2ndex_ovenfrenchtoast) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-turn) 
 	(executed-preheat oven c) 
 	(executed-dip side mixture) 
 	(executed-bake minutes minutes) 
 	(executed-bake minutes) 
 	(=(number-executed-turn) 0) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-mix) 0) 
 	(=(number-executedDObIOb-preheat oven c) 0) 
 	(=(number-executedDObIOb-dip side mixture) 0) 
 	(=(number-executedDObIOb-place pan pan) 0) 
 	(=(number-executedDObIOb-bake minutes minutes) 0) 
 	(=(number-executedDObIOb-more minutes minutes) 0) 
 	(=(number-executedIOb-bake minutes) 0) 
 	(property-to c) 
 	(property-over margarine) 
 	(property-into mixture) 
 	(property-of bread) 
 	(property-in pan) 
 	(property-for minutes) 
 	(property-npmod minutes) 
 	(property-baking pan) 
 	(property-orange juice) 
 	(property-orange rind) 
 	(property-prepared pan) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-turn) 1) 
 	(=(number-executed-serve) 1) 
 	(=(number-executed-mix) 1) 
 	(=(number-executedDObIOb-preheat oven c) 1) 
 	(=(number-executedDObIOb-dip side mixture) 1) 
 	(=(number-executedDObIOb-place pan pan) 1) 
 	(=(number-executedDObIOb-bake minutes minutes) 1) 
 	(=(number-executedDObIOb-more minutes minutes) 1) 
 	(=(number-executedIOb-bake minutes) 1) 
 	(finished)
)) 
 
)