(define (problem 2ndex_friedFrenchToast) 
 
 (:domain 2ndex_friedFrenchToast) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-crack) 
 	(executed-heat) 
 	(executed-set stove heat) 
 	(executed-dip bread mixture) 
 	(executed-coat bread mixture) 
 	(executed-place slice pan) 
 	(executed-put toast plate) 
 	(executed-turn heat) 
 	(executed-cook toast) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-heat) 0) 
 	(=(number-executed-extract) 0) 
 	(=(number-executed-crack) 0) 
 	(=(number-executedDObIOb-set stove heat) 0) 
 	(=(number-executedDObIOb-dip bread mixture) 0) 
 	(=(number-executedDObIOb-coat bread mixture) 0) 
 	(=(number-executedDObIOb-place slice pan) 0) 
 	(=(number-executedDObIOb-put toast plate) 0) 
 	(=(number-executedIOb-add milk) 0) 
 	(=(number-executedIOb-add cinnamon) 0) 
 	(=(number-executedIOb-turn heat) 0) 
 	(=(number-executedIOb-cook toast) 0) 
 	(=(serve-saliency) 1) 
 	(=(heat-saliency) 1) 
 	(=(extract-saliency) 1) 
 	(=(crack-saliency) 1) 
 	(=(set-saliency stove heat) 1) 
 	(=(dip-saliency bread mixture) 1) 
 	(=(coat-saliency bread mixture) 1) 
 	(=(place-saliency slice pan) 1) 
 	(=(put-saliency toast plate) 1) 
 	(=(add-saliency milk) 1) 
 	(=(add-saliency cinnamon) 1) 
 	(=(turn-saliency heat) 1) 
 	(=(cook-saliency toast) 1) 
 	(property-to heat) 
 	(property-into bowl) 
 	(property-to medium) 
 	(property-into mixture) 
 	(property-with mixture) 
 	(property-onto pan) 
 	(property-on plate) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-heat) 1) 
 	(=(number-executed-extract) 1) 
 	(=(number-executed-crack) 1) 
 	(=(number-executedDObIOb-set stove heat) 1) 
 	(=(number-executedDObIOb-dip bread mixture) 1) 
 	(=(number-executedDObIOb-coat bread mixture) 1) 
 	(=(number-executedDObIOb-place slice pan) 1) 
 	(=(number-executedDObIOb-put toast plate) 1) 
 	(=(number-executedIOb-add milk) 1) 
 	(=(number-executedIOb-add cinnamon) 1) 
 	(=(number-executedIOb-turn heat) 1) 
 	(=(number-executedIOb-cook toast) 1) 
 	(finished)
)) 
 
)