(define (problem 2ndex_fruitsushi) 
 
 (:domain 2ndex_fruitsushi) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-lower) 
 	(executed-continue) 
 	(executed-cool) 
 	(executed-cut) 
 	(executed-roll) 
 	(executed-empty rice bowl) 
 	(executed-spread rice wrap) 
 	(executed-fill it) 
 	(executed-allow rice) 
 	(executed-place slices) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-roll) 0) 
 	(=(number-executed-lower) 0) 
 	(=(number-executed-cut) 0) 
 	(=(number-executed-cool) 0) 
 	(=(number-executed-continue) 0) 
 	(=(number-executedDObIOb-empty rice bowl) 0) 
 	(=(number-executedDObIOb-add water saucepan) 0) 
 	(=(number-executedDObIOb-add rice saucepan) 0) 
 	(=(number-executedDObIOb-add salt saucepan) 0) 
 	(=(number-executedDObIOb-add sugar saucepan) 0) 
 	(=(number-executedDObIOb-spread rice wrap) 0) 
 	(=(number-executedDObIOb-wait minutes minutes) 0) 
 	(=(number-executedIOb-fill it) 0) 
 	(=(number-executedIOb-wash rice) 0) 
 	(=(number-executedIOb-cook rice) 0) 
 	(=(number-executedIOb-add milk) 0) 
 	(=(number-executedIOb-allow rice) 0) 
 	(=(number-executedIOb-place slices) 0) 
 	(=(serve-saliency) 1) 
 	(=(roll-saliency) 1) 
 	(=(lower-saliency) 1) 
 	(=(cut-saliency) 1) 
 	(=(cool-saliency) 1) 
 	(=(continue-saliency) 1) 
 	(=(empty-saliency rice bowl) 1) 
 	(=(add-saliency water saucepan) 1) 
 	(=(add-saliency rice saucepan) 1) 
 	(=(add-saliency salt saucepan) 1) 
 	(=(add-saliency sugar saucepan) 1) 
 	(=(spread-saliency rice wrap) 1) 
 	(=(wait-saliency minutes minutes) 1) 
 	(=(fill-saliency it) 1) 
 	(=(wash-saliency rice) 1) 
 	(=(cook-saliency rice) 1) 
 	(=(add-saliency milk) 1) 
 	(=(allow-saliency rice) 1) 
 	(=(place-saliency slices) 1) 
 	(property-into bowl) 
 	(property-with water) 
 	(property-poss your) 
 	(property-to saucepan) 
 	(property-for minutes) 
 	(property-onto wrap) 
 	(property-coconut milk) 
 	(property-plastic wrap) 
 	(property-wash use) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-roll) 1) 
 	(=(number-executed-lower) 1) 
 	(=(number-executed-cut) 1) 
 	(=(number-executed-cool) 1) 
 	(=(number-executed-continue) 1) 
 	(=(number-executedDObIOb-empty rice bowl) 1) 
 	(=(number-executedDObIOb-add water saucepan) 1) 
 	(=(number-executedDObIOb-add rice saucepan) 1) 
 	(=(number-executedDObIOb-add salt saucepan) 1) 
 	(=(number-executedDObIOb-add sugar saucepan) 1) 
 	(=(number-executedDObIOb-spread rice wrap) 1) 
 	(=(number-executedDObIOb-wait minutes minutes) 1) 
 	(=(number-executedIOb-fill it) 1) 
 	(=(number-executedIOb-wash rice) 1) 
 	(=(number-executedIOb-cook rice) 1) 
 	(=(number-executedIOb-add milk) 1) 
 	(=(number-executedIOb-allow rice) 1) 
 	(=(number-executedIOb-place slices) 1) 
 	(finished)
)) 
 
)