(define (problem 2ndex_ChocolateCookies) 
 
 (:domain 2ndex_ChocolateCookies) 
 
 (:init 
 	 (not (finished)) 
 	 (executed-chill) 
 	(executed-preheat oven f) 
 	(executed-cover sheet paper) 
 	(executed-cover bowl wrap) 
 	(executed-pour ingredients) 
 	(=(number-executed-serve) 0) 
 	(=(number-executed-chill) 0) 
 	(=(number-executedDObIOb-preheat oven f) 0) 
 	(=(number-executedDObIOb-cover sheet paper) 0) 
 	(=(number-executedDObIOb-cover bowl wrap) 0) 
 	(=(number-executedDObIOb-drop dough sheet) 0) 
 	(=(number-executedDObIOb-bake cookies minutes) 0) 
 	(=(number-executedDObIOb-cool cookies minutes) 0) 
 	(=(number-executedDObIOb-blend minutes minutes) 0) 
 	(=(number-executedIOb-take mixer) 0) 
 	(=(number-executedIOb-cream butter) 0) 
 	(=(number-executedIOb-cream sugar) 0) 
 	(=(number-executedIOb-take bowl) 0) 
 	(=(number-executedIOb-combine ingredients) 0) 
 	(=(number-executedIOb-combine flour) 0) 
 	(=(number-executedIOb-combine cocoa) 0) 
 	(=(number-executedIOb-combine salt) 0) 
 	(=(number-executedIOb-combine soda) 0) 
 	(=(number-executedIOb-combine powder) 0) 
 	(=(number-executedIOb-pour ingredients) 0) 
 	(=(number-executedIOb-fold chips) 0) 
 	(=(number-executedIOb-fold marshmallows) 0) 
 	(=(serve-saliency) 1) 
 	(=(chill-saliency) 1) 
 	(=(preheat-saliency oven f) 1) 
 	(=(cover-saliency sheet paper) 1) 
 	(=(cover-saliency bowl wrap) 1) 
 	(=(drop-saliency dough sheet) 1) 
 	(=(bake-saliency cookies minutes) 1) 
 	(=(cool-saliency cookies minutes) 1) 
 	(=(blend-saliency minutes minutes) 1) 
 	(=(take-saliency mixer) 1) 
 	(=(cream-saliency butter) 1) 
 	(=(cream-saliency sugar) 1) 
 	(=(take-saliency bowl) 1) 
 	(=(combine-saliency ingredients) 1) 
 	(=(combine-saliency flour) 1) 
 	(=(combine-saliency cocoa) 1) 
 	(=(combine-saliency salt) 1) 
 	(=(combine-saliency soda) 1) 
 	(=(combine-saliency powder) 1) 
 	(=(pour-saliency ingredients) 1) 
 	(=(fold-saliency chips) 1) 
 	(=(fold-saliency marshmallows) 1) 
 	(property-to f) 
 	(property-with paper) 
 	(property-with wrap) 
 	(property-on sheet) 
 	(property-for minutes) 
 	(property-baking sheet) 
 	(property-electric mixer) 
 	(property-brown sugar) 
 	(property-white sugar) 
 	(property-separate bowl) 
 	(property-hot cocoa) 
 	(property-baking soda) 
 	(property-baking powder) 
 	(property-dry ingredients) 
 	(property-plastic wrap) 
 	 
 	) 
 
 (:goal (and
 	 (=(number-executed-serve) 1) 
 	(=(number-executed-chill) 1) 
 	(=(number-executedDObIOb-preheat oven f) 1) 
 	(=(number-executedDObIOb-cover sheet paper) 1) 
 	(=(number-executedDObIOb-cover bowl wrap) 1) 
 	(=(number-executedDObIOb-drop dough sheet) 1) 
 	(=(number-executedDObIOb-bake cookies minutes) 1) 
 	(=(number-executedDObIOb-cool cookies minutes) 1) 
 	(=(number-executedDObIOb-blend minutes minutes) 1) 
 	(=(number-executedIOb-take mixer) 1) 
 	(=(number-executedIOb-cream butter) 1) 
 	(=(number-executedIOb-cream sugar) 1) 
 	(=(number-executedIOb-take bowl) 1) 
 	(=(number-executedIOb-combine ingredients) 1) 
 	(=(number-executedIOb-combine flour) 1) 
 	(=(number-executedIOb-combine cocoa) 1) 
 	(=(number-executedIOb-combine salt) 1) 
 	(=(number-executedIOb-combine soda) 1) 
 	(=(number-executedIOb-combine powder) 1) 
 	(=(number-executedIOb-pour ingredients) 1) 
 	(=(number-executedIOb-fold chips) 1) 
 	(=(number-executedIOb-fold marshmallows) 1) 
 	(finished)
)) 
 
)